# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: dull pointer exception
email: ceciliawatt@gmail.com
name: Cecilia Saixue Watt
description: > # this means to ignore newlines until "baseurl:"
  tk
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://cswatt.github.io" # the base hostname & protocol for your site
twitter_username: ceciliasaixue
github_username:  cswatt

# Build settings
markdown: kramdown
